CREATE DATABASE crud_php;
USE crud_php;

CREATE TABLE usuario(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
data_nascimento DATE NOT NULL,
senha VARCHAR(255) NOT NULL
);

SELECT * FROM usuario;
TRUNCATE usuario;